addr = "0.0.0.0:50000"
prover_addrs = ["127.0.0.1:50001", "127.0.0.1:50002"]
snark_addrs = ["127.0.0.1:50051"]
base_dir = "/tmp/zkm/test/test_proof"
ca_cert_path = "tools/certs/ca.pem"
cert_path = "tools/certs/stage.pem"
key_path = "tools/certs/stage.key"